### ISSUE TITLE
Add support for binance.us

### ISSUE THREAD

**Issue by Noah-Franks** [Ashlar/binance-api-node#246]
Currently there's no way to change the endpoint to https://api.binance.us

That in the constructor is all that's needed to make this work for Americans.

**Comment by balthazar** [comment]
I can't wait for your PR

**Comment by Noah-Franks** [comment]
Wow, okay. Your loss then.

**Comment by balthazar** [comment]
You said it's easy so why don't you submit one?

**Comment by dwmcqueen** [comment]
Wouldn't you just need to change this;

const BASE = 'https://api.binance.com'
const FUTURES = 'https://fapi.binance.com'

In the http-client.js code?

**Comment by djheru** [comment]
@balthazar I see the `http-client` default export already accepts an option for the `httpBase` and `httpFutures` endpoints. I could submit a PR that does the same for the websocket client if that would be useful.

**Comment by balthazar** [comment]
@djheru Yeah would be useful thanks :)

Closing this issue as it actually already supports it

**Comment by Aaronik** [comment]
@balthazar, I'm looking for this same functionality and I cannot find in the documentation how to do it. This issue is the first thing I found that mentioned it. I see you closed it because the library already supports this functionality, but you don't mention how to do it. Saying "It already does" and closing the ticket without mentioning how is really, really unhelpful.
